import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";

import "./globals.css";

import {PrimeReactProvider} from 'primereact/api';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create PrimeActive",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="cupcake">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <PrimeReactProvider>
            {children}
        </PrimeReactProvider>
        </body>
        </html>
    );
}
